# Use an official Python runtime as the base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the backend dependencies
COPY backend/requirements.txt /app/requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire backend code
COPY backend/ /app

# Expose the Flask app port
EXPOSE 5000

# # Set API base URL for Flask
# ENV API_BASE_URL=http://backend:5000

# Run the Flask app
CMD ["python", "app.py"]